version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ipfsmanager
      MYSQL_DATABASE: u3191982_default
      MYSQL_USER: u3191982_default
      MYSQL_PASSWORD: M2i979QhnyGwgAb2
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  strapi:
    build:
      context: ./backend
    container_name: strapi
    depends_on:
      - mysql
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: u3191982_default
      DATABASE_USERNAME: u3191982_default
      DATABASE_PASSWORD: M2i979QhnyGwgAb2
      NODE_ENV: production

      APP_KEYS: R3vNgwTz/KNmud6re9tB5w==,Mn+ZCUuGC+xh90Hi71J+bA==,wSQusvCJSNC0wuKv/9/j+Q==,DhEg4l3HarOerMGe7Kqveg==
      API_TOKEN_SALT: W2V4CvEIvkGe99usiK/edw==
      ADMIN_JWT_SECRET: Kd/QFG4qnONBpMuVsc75SA==
      TRANSFER_TOKEN_SALT: 5do+YQAiw9sR73KXIJNf9A==
      ENCRYPTION_KEY: D7gMg1vDcCR4hnj7WtIjlA==
      JWT_SECRET: EWc7NAn3CzT3DEfBwJxWBw==
    
    volumes:
      - ./backend:/app
      - strapi_uploads:/app/public/uploads
    ports:
      - "1337:1337"

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - strapi_uploads:/app/public/uploads
    depends_on:
      - strapi

volumes:
  mysql_data:
  strapi_uploads:


